/**
 * Generates packages/core/src/measure/tables.ts from the latest Unicode UCD files.
 *
 * Run with: pnpm gen:unicode
 *
 * Sources (UCD latest):
 *   - EastAsianWidth.txt           (UAX #11) — wide / fullwidth detection
 *   - emoji/emoji-data.txt         — Extended_Pictographic + Emoji_Presentation
 *   - auxiliary/GraphemeBreakProperty.txt (UAX #29) — grapheme cluster properties
 *   - DerivedCoreProperties.txt    — Default_Ignorable_Code_Point (zero-width)
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const UCD = 'https://www.unicode.org/Public/UCD/latest/ucd';
const SOURCES = {
  eaw: `${UCD}/EastAsianWidth.txt`,
  emoji: `${UCD}/emoji/emoji-data.txt`,
  gbp: `${UCD}/auxiliary/GraphemeBreakProperty.txt`,
  dcp: `${UCD}/DerivedCoreProperties.txt`,
};

const OUTPUT = resolve('packages/core/src/measure/tables.ts');

type Range = readonly [start: number, end: number];

async function fetchText(url: string): Promise<string> {
  console.log(`fetch ${url}`);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`fetch failed ${res.status}: ${url}`);
  return res.text();
}

/**
 * Parses a UCD file. Each line is either a comment (#) or:
 *   <codepoint>      ; <prop> # ...
 *   <start>..<end>   ; <prop> # ...
 * Returns ranges grouped by property value.
 */
function parseUcd(text: string): Map<string, Range[]> {
  const out = new Map<string, Range[]>();
  for (const rawLine of text.split('\n')) {
    const hashIdx = rawLine.indexOf('#');
    const line = (hashIdx === -1 ? rawLine : rawLine.slice(0, hashIdx)).trim();
    if (!line) continue;
    const parts = line.split(';').map((s) => s.trim());
    if (parts.length < 2) continue;
    const cp = parts[0]!;
    const prop = parts[1]!;
    const dotdot = cp.indexOf('..');
    const start = Number.parseInt(dotdot === -1 ? cp : cp.slice(0, dotdot), 16);
    const end = Number.parseInt(dotdot === -1 ? cp : cp.slice(dotdot + 2), 16);
    if (!Number.isFinite(start) || !Number.isFinite(end)) continue;
    let arr = out.get(prop);
    if (!arr) {
      arr = [];
      out.set(prop, arr);
    }
    arr.push([start, end]);
  }
  return out;
}

/** Merge adjacent / overlapping ranges. Input ranges may be unsorted. */
function mergeRanges(ranges: Range[]): Range[] {
  if (ranges.length === 0) return [];
  const sorted = [...ranges].sort((a, b) => a[0] - b[0]);
  const merged: [number, number][] = [];
  let [curStart, curEnd] = sorted[0]!;
  for (let i = 1; i < sorted.length; i++) {
    const [s, e] = sorted[i]!;
    if (s <= curEnd + 1) {
      if (e > curEnd) curEnd = e;
    } else {
      merged.push([curStart, curEnd]);
      curStart = s;
      curEnd = e;
    }
  }
  merged.push([curStart, curEnd]);
  return merged;
}

/** Encode an array of ranges as a flat Uint32Array-friendly literal. */
function emitRanges(name: string, ranges: Range[]): string {
  const flat = ranges.flat();
  const lines: string[] = [];
  for (let i = 0; i < flat.length; i += 16) {
    const chunk = flat
      .slice(i, i + 16)
      .map((n) => `0x${n.toString(16)}`)
      .join(', ');
    lines.push(`  ${chunk},`);
  }
  return `export const ${name}: readonly number[] = [\n${lines.join('\n')}\n];\n`;
}

async function main() {
  const [eawText, emojiText, gbpText, dcpText] = await Promise.all([
    fetchText(SOURCES.eaw),
    fetchText(SOURCES.emoji),
    fetchText(SOURCES.gbp),
    fetchText(SOURCES.dcp),
  ]);

  const eaw = parseUcd(eawText); // F, W, A, H, Na, N
  const emoji = parseUcd(emojiText); // Emoji, Emoji_Presentation, Extended_Pictographic, Emoji_Modifier, Emoji_Modifier_Base, Emoji_Component
  const gbp = parseUcd(gbpText); // Prepend, CR, LF, Control, Extend, Regional_Indicator, SpacingMark, L, V, T, LV, LVT, ZWJ
  const dcp = parseUcd(dcpText); // Default_Ignorable_Code_Point and others

  const wide = mergeRanges([...(eaw.get('W') ?? []), ...(eaw.get('F') ?? [])]);
  const extPict = mergeRanges(emoji.get('Extended_Pictographic') ?? []);
  const emojiPres = mergeRanges(emoji.get('Emoji_Presentation') ?? []);

  const grapheme = {
    Prepend: mergeRanges(gbp.get('Prepend') ?? []),
    Control: mergeRanges(gbp.get('Control') ?? []),
    Extend: mergeRanges(gbp.get('Extend') ?? []),
    SpacingMark: mergeRanges(gbp.get('SpacingMark') ?? []),
    Regional_Indicator: mergeRanges(gbp.get('Regional_Indicator') ?? []),
    L: mergeRanges(gbp.get('L') ?? []),
    V: mergeRanges(gbp.get('V') ?? []),
    T: mergeRanges(gbp.get('T') ?? []),
    LV: mergeRanges(gbp.get('LV') ?? []),
    LVT: mergeRanges(gbp.get('LVT') ?? []),
    ZWJ: mergeRanges(gbp.get('ZWJ') ?? []),
  };

  const defaultIgnorable = mergeRanges(dcp.get('Default_Ignorable_Code_Point') ?? []);

  const banner = `// AUTO-GENERATED by tools/generate-unicode-tables.ts.
// DO NOT EDIT BY HAND. Run \`pnpm gen:unicode\` to regenerate.
// Source: Unicode UCD ${SOURCES.eaw.split('/UCD/')[1]?.split('/')[0] ?? 'latest'}.

`;

  const sections: ReadonlyArray<readonly [name: string, ranges: Range[]]> = [
    ['WIDE_RANGES', wide],
    ['EXT_PICTOGRAPHIC_RANGES', extPict],
    ['EMOJI_PRESENTATION_RANGES', emojiPres],
    ['GB_PREPEND', grapheme.Prepend],
    ['GB_CONTROL', grapheme.Control],
    ['GB_EXTEND', grapheme.Extend],
    ['GB_SPACINGMARK', grapheme.SpacingMark],
    ['GB_REGIONAL_INDICATOR', grapheme.Regional_Indicator],
    ['GB_L', grapheme.L],
    ['GB_V', grapheme.V],
    ['GB_T', grapheme.T],
    ['GB_LV', grapheme.LV],
    ['GB_LVT', grapheme.LVT],
    ['GB_ZWJ', grapheme.ZWJ],
    ['DEFAULT_IGNORABLE', defaultIgnorable],
  ];
  const body = sections.map(([name, ranges]) => emitRanges(name, ranges)).join('\n');

  writeFileSync(OUTPUT, banner + body);
  console.log(`wrote ${OUTPUT}`);
  console.log(`  wide ranges:               ${wide.length}`);
  console.log(`  extended pictographic:     ${extPict.length}`);
  console.log(`  emoji presentation:        ${emojiPres.length}`);
  console.log(`  grapheme Extend:           ${grapheme.Extend.length}`);
  console.log(`  grapheme Regional ind.:    ${grapheme.Regional_Indicator.length}`);
  console.log(`  default ignorable:         ${defaultIgnorable.length}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
